# Generated by Django 5.1.5 on 2025-01-20 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('ph_number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ammount', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreApi.usermodel')),
            ],
            options={
                'db_table': 'PurchaseDetails',
            },
        ),
        migrations.CreateModel(
            name='CreditDetailsModel',
            fields=[
                ('credit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('credit_limit', models.IntegerField(default=0)),
                ('pending_dues', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreApi.usermodel')),
            ],
            options={
                'db_table': 'CreditDetails',
            },
        ),
    ]
