# Generated by Django 5.1.5 on 2025-01-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0002_alter_creditdetailsmodel_credit_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditdetailsmodel',
            old_name='pending_dues',
            new_name='max_credit_limit',
        ),
    ]
