# Generated by Django 5.1.5 on 2025-01-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0003_rename_pending_dues_creditdetailsmodel_max_credit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='name',
        ),
    ]
