# Generated by Django 5.1.5 on 2025-01-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0004_remove_purchasemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coreApi.usermodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completetd', models.BooleanField(verbose_name=False)),
                ('duration', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApi.purchasemodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApi.usermodel')),
            ],
            options={
                'db_table': 'EMIDetails',
            },
        ),
    ]
