# Generated by Django 5.1.5 on 2025-01-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0005_alter_purchasemodel_user_id_emimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emimodel',
            old_name='is_completetd',
            new_name='is_completeted',
        ),
    ]
