# Generated by Django 5.1.5 on 2025-01-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0006_rename_is_completetd_emimodel_is_completeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emimodel',
            name='is_completeted',
        ),
        migrations.AddField(
            model_name='emimodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
