# Generated by Django 5.1.5 on 2025-01-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0007_remove_emimodel_is_completeted_emimodel_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emimodel',
            old_name='duration',
            new_name='duration_in_months',
        ),
    ]
